doc(mobile,features) : add that mobile overlay isn't supported yet
PlayEveryWare/eos_plugin_for_unity pull request #1046
Opened 2024-12-06 00:26 UTC by arthur740212

As of EOSSDK 1.16.4 overlay on mobile is not supported yet. That includes Social Overlay and Store Overlay

2024-12-07 05:56 UTC, paulhazen approved these changes

2024-12-07 06:00 UTC, paulhazen requested changes
The table included in the `README.md` file is actually from the `eos_features.md` document. If it is to be updated in one place, then that change should be reflected in both files.

2024-12-10 22:45 UTC, WispyMouse approved these changes

2024-12-13 18:43 UTC, andrew-hirata-playeveryware approved these changes

2024-12-13 20:26 UTC, paulhazen approved these changes

2024-12-16 22:58 UTC, merged