fix: Implement distinction between authentication on different interfaces within EOS SDK.
PlayEveryWare/eos_plugin_for_unity pull request #1051
Opened 2024-12-12 07:21 UTC by paulhazen

2025-01-07 00:42 UTC, WispyMouse commented
I opened the Achievements sample, and it didn't show any achievements until I pressed "Refresh Data". Could this suggest that it's not set up to listen to the correct events or that the correct events aren't firing?

2025-01-07 00:52 UTC, WispyMouse commented on com.playeveryware.eos/Runtime/Core/Authentication/AuthenticationEventObserver.cs
> +            if ((ObservedLoginInterfaces & args.Interface) != ObservedLoginInterfaces)
With the Achievement Service and Player Data Storage set to "AuthOrConnect", it appears as though this doesn't fire because "AuthOrConnect" is never equal to exactly "Auth" or "Connect". Should we adjust this bitwise logic so that this would be true in those cases?

2025-01-07 00:54 UTC, WispyMouse commented
Is it within the scope of this PR to set each of the services that exist to use the new parameter, or should that be done separately? Achievement for example should be a Connect rather than an AuthAndConnect. We could do a sweep of services and align them with their intended logins.

2025-01-07 19:32 UTC, paulhazen commented on com.playeveryware.eos/Runtime/Core/Authentication/AuthenticationEventObserver.cs
> +            if ((ObservedLoginInterfaces & args.Interface) != ObservedLoginInterfaces)
I have addressed this issue by removing the `AuthOrConnect` value - and instead just having individual values for each type - and having the `AuthenticationEventObserver` store an array of acceptable interfaces to listen to.

If the fix is acceptable to you, please mark this conversation as resolved :)

2025-01-07 22:11 UTC, WispyMouse commented on com.playeveryware.eos/Runtime/Core/Authentication/AuthenticationEventObserver.cs
> +            if (ObservedLoginInterfaces.Contains(args.Interface))
I think this has a boolean logic problem; it's preventing things that _contain_ the interface.

2025-01-07 22:11 UTC, WispyMouse commented on com.playeveryware.eos/Runtime/Core/Authentication/AuthenticationEventObserver.cs
> +            if ((ObservedLoginInterfaces & args.Interface) != ObservedLoginInterfaces)
This approach is satisfactory, though please see new comment in regards to the boolean logic.

2025-01-08 18:30 UTC, paulhazen commented on com.playeveryware.eos/Runtime/Core/Authentication/AuthenticationEventObserver.cs
> +            if (ObservedLoginInterfaces.Contains(args.Interface))
I have updated the implementation to avoid use of bitwise operations altogether - instead the services now accept a `params` value for the constructor that allows multiple `LoginInterfaces` values to be provided to indicate what the required login stuff is.

2025-01-08 18:38 UTC, paulhazen commented on com.playeveryware.eos/Runtime/Core/Authentication/AuthenticationEventObserver.cs
> +    using System.Linq;
This is suspicious - does linq need to be used?

2025-01-08 18:39 UTC, paulhazen commented on com.playeveryware.eos/Runtime/Core/Common/Disposable.cs
> +    public abstract class Disposable : IDisposable
This feels like a refactor - perhaps this work would be better suited to be outside of this PR.

2025-01-08 18:45 UTC, paulhazen commented on com.playeveryware.eos/Runtime/Core/Authentication/AuthenticationEventObserver.cs
> +        protected LoginInterfaces[] ObservedLoginInterfaces { get; }
This is a strange approach to take - we should re-evaluate use of bitwise operations on a flags enum.

2025-01-08 20:40 UTC, paulhazen commented on com.playeveryware.eos/Runtime/Core/Common/Disposable.cs
> +    public abstract class Disposable : IDisposable
Not a refactor - because existing implementations of the `IDisposable` interface were not changed to use this - instead just the newly introduced class that requires the [disposable pattern](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/dispose-pattern) uses it.

2025-01-09 00:04 UTC, paulhazen commented on com.playeveryware.eos/Runtime/Core/Authentication/AuthenticationEventObserver.cs
> +    using System.Linq;
Nope - it has been removed.

2025-01-09 00:05 UTC, paulhazen commented on com.playeveryware.eos/Runtime/Core/Authentication/AuthenticationEventObserver.cs
> +        protected LoginInterfaces[] ObservedLoginInterfaces { get; }
Implementation was restored to make use of bitflags - as is appropriate.

2025-01-13 21:28 UTC, WispyMouse requested changes
Setting to "Request changes" while pending fixes.

2025-02-10 18:45 UTC, WispyMouse approved these changes

2025-02-11 18:25 UTC, andrew-hirata-playeveryware approved these changes

2025-02-13 20:05 UTC, merged