feat(config): Config Verification Prebuild Step
PlayEveryWare/eos_plugin_for_unity pull request #158
Opened 2022-10-24 22:24 UTC by Raxnam

A prebuild script that checks for a valid platform config file before starting the build. This throws the error and stops the build before the build actually starts instead of after the build is done

2022-10-24 23:05 UTC, pew-dahs requested changes

2022-10-24 23:05 UTC, pew-dahs commented on Assets/Plugins/Source/Editor/PreProcessConfigConfirmation.cs
> +        Debug.Log("PreProcessConfigConfirmation_Windows.OnPreprocessBuild for target " + report.summary.platform + " at path " + System.IO.Directory.GetCurrentDirectory());
I'm assuming this should be PreProcessingConfigConfirmation by itself instead of _Windows attached to it? Unless there's going to be platform specific pre process confirmations.

2022-10-24 23:05 UTC, pew-dahs commented on Assets/Plugins/Source/Editor/PreProcessConfigConfirmation.cs
> +            case BuildTarget.StandaloneWindows:
You can simplify this copy/pasted switch to instead use a readonly dictionary (or you could create a local one) of the target and the config file, something like
```
Dictionary<BuildTarget, string> buildFileMap = new Dictionary<BuildTarget, string> {
  { BuildTarget.StandaloneWindows, "Assets/StreamingAssets/EOS/EpicOnlineServicesConfig.json" },
  { BuildTarget.StandaloneWindows64, "Assets/StreamingAssets/EOS/EpicOnlineServicesConfig.json" },
  ...
}
```
Then the whole function can be simplified to
```
if (System.IO.File.Exists(buildFileMap[target]))
{
    Debug.Log("PreProcessConfigConfirmation.OnPreprocessBuild for target " + target + " config file exists");
}
else
{
    Debug.LogError("PreProcessConfigConfirmation.OnPreprocessBuild for target " + target + " config file is missing");
    throw new BuildFailedException("Config file is missing, refer to above message");
}
```
and you can remove the extra functions at the end. In this way, when we need to add new platforms, we don't have to copy/paste a section, but add a new line to the dictionary (or uncomment a line).

2022-10-24 23:11 UTC, pew-dahs commented on Assets/Plugins/Source/Editor/PreProcessConfigConfirmation.cs
> +            case BuildTarget.StandaloneWindows:
Also, you should also have a default check for the case where the target platform isn't covered with some error message for that too.

2022-10-25 19:21 UTC, Raxnam commented on Assets/Plugins/Source/Editor/PreProcessConfigConfirmation.cs
> +        Debug.Log("PreProcessConfigConfirmation_Windows.OnPreprocessBuild for target " + report.summary.platform + " at path " + System.IO.Directory.GetCurrentDirectory());
Ah yea, I had initially planned to have one for each platform, but the preprocess function provides the target so everything can be done in one function.

2022-10-25 19:22 UTC, Raxnam commented on Assets/Plugins/Source/Editor/PreProcessConfigConfirmation.cs
> +            case BuildTarget.StandaloneWindows:
Thanks, I'm not too familiar with c# data structures, I just know it doesn't have a map, but that works really well.

2022-10-25 20:33 UTC, pew-dahs commented on Assets/Plugins/Source/Editor/PreProcessConfigConfirmation.cs
> +            case BuildTarget.StandaloneWindows:
A dictionary in C# is the same as a map in C++, just a different name.

2022-10-25 20:41 UTC, pew-dahs approved these changes
Looks good. Just need to remove an extra line that's there.

2022-10-25 20:41 UTC, pew-dahs commented on Assets/Plugins/Source/Editor/PreProcessConfigConfirmation.cs
> +        file
You should remove this line.

2022-10-25 20:41 UTC, pew-dahs commented on Assets/Plugins/Source/Editor/PreProcessConfigConfirmation.cs
> +        fileDictionary.Add(BuildTarget.StandaloneWindows,   "Assets/StreamingAssets/EOS/EpicOnlineServicesConfig.json");
nit: You can actually initialize a dictionary directly without adding key/value pairs after. No need to change it, but nice to know about C# initialization.
```
Dictionary<BuildTarget, string> fileDictionary = new Dictionary<BuildTarget, string> {
  { BuildTarget.StandaloneWindows, "Assets/StreamingAssets/EOS/EpicOnlineServicesConfig.json" },
  ...
};
```

2022-10-27 23:14 UTC, andrew-hirata-playeveryware approved these changes

2022-11-01 18:47 UTC, merged