Performance Stress Test Implementation
PlayEveryWare/eos_plugin_for_unity pull request #179
Opened 2022-12-12 23:52 UTC by Raxnam

Implemented stress tests
- CPU Stress Test 
     Automatic core detection or user scalable
     Target specific utilization targets (+- 5%)
- GPU Stress Test
- Memory Utilization Test
     User scalable memory allocation
     Note: The memory once allocated is still held onto by Unity and not returned to the system regardless of it being released by the garbage collector

2022-12-14 03:13 UTC, pew-dahs reviewed
The biggest thing I see is the large change to the gitignore that could be done with a single line. Everything else is okay other that some nitpicks and file naming.

2022-12-14 03:13 UTC, pew-dahs commented on Assets/Scripts/Util/RotateObject.cs
> +    // Start is called before the first frame update
If there's nothing to do for Start, should just remove it.

2022-12-14 03:13 UTC, pew-dahs commented on Assets/Scripts/PerformanceStressTest.cs
> +
nit: Extra white space

2022-12-14 03:13 UTC, pew-dahs commented on Assets/Scripts/PerformanceStressTest.cs
> +
nit: Extra whitespace

2022-12-14 03:13 UTC, pew-dahs commented on Assets/Scripts/PerformanceStressTest.cs
> +
nit: Extra whitespace

2022-12-14 03:13 UTC, pew-dahs commented on Assets/Materials/New Lighting Settings.lighting
> +%YAML 1.1
I feel like this file and the shader graph should have proper names instead of "New File."

2022-12-14 03:13 UTC, pew-dahs commented on .gitignore
> +Assets/TextMesh Pro/Sprites/EmojiOne.png.meta
All the TextMeshPro files can be ignored with `[Aa]ssets/TextMesh*Pro/` instead of adding each file individually.

2022-12-14 03:13 UTC, pew-dahs commented on Assets/Scripts/UI/UISliderToText.cs
> +    public void updateText()
nit: You can use dynamic values from a slider event from the Unity property window assuming you're using that, which would eliminate the need to keep track of the slider. However, if you're calling this not from the Unity event, then ignore this.

2023-01-21 00:04 UTC, andrew-hirata-playeveryware reviewed
We need to add a license file for the images: 

```
PLAYEVERYWARE and [image001.png] are trademarks of PlayEveryWare, Inc. 
Subject to the term and conditions of [these Terms of Use; this Agreement] [Developers] may 
place such Marks on [projects] for the sole purpose of identifying PlayEveryWare as the 
owner and copyright holder of the [PlugIn] and for no other business or non-business 
purposes whatsoever and no other goods or services whatsoever. 
```

2023-01-21 00:04 UTC, andrew-hirata-playeveryware commented on Assets/Materials/New Shader Graph.shadergraph
> +{
This file could use a proper name.

2023-01-21 00:38 UTC, dammittom requested changes
Could we rename these files to "PlayEveryWare-logo"? This would better align with company branding guidelines, which would also help enforce other users to comply with them as well.

2023-01-26 19:30 UTC, andrew-hirata-playeveryware commented on Assets/Materials/PlayEveryWareLicense.txt
> +PLAYEVERYWARE, PlayEveryWare-normalmap.png, and PlayEveryWare-logo.png are trademarks of PlayEveryWare, Inc.
Hey @dammittom, Does this look good to you?

2023-01-26 19:55 UTC, dammittom commented on Assets/Materials/PlayEveryWareLicense.txt
> +PLAYEVERYWARE, PlayEveryWare-normalmap.png, and PlayEveryWare-logo.png are trademarks of PlayEveryWare, Inc.
This looks great! Thank you!

2023-02-10 01:59 UTC, andrew-hirata-playeveryware approved these changes

2023-02-10 02:35 UTC, dammittom approved these changes

2023-03-07 00:51 UTC, andrew-hirata-playeveryware commented
Merged in manually to resolve merge conflicts at 2b8c40da91cfb6e17ae448d865a9dc8312f5e031

2023-03-07 00:51 UTC, closed without merging