doc : login for public platforms
PlayEveryWare/eos_plugin_for_unity pull request #271
Opened 2023-05-03 01:38 UTC by arthur740212

2023-05-04 18:36 UTC, andrew-hirata-playeveryware requested changes

2023-05-04 18:36 UTC, andrew-hirata-playeveryware commented on docs/readme_login.md
> +* EOS Platform Interface must be initilaized before performing a login
I think we need to specify what 'init' means here.
i.e. needing to have the EOSManager attached to a scene that is being run.

2023-05-04 18:36 UTC, andrew-hirata-playeveryware commented on docs/readme_login.md
> +* **Dev Auth**(`EOS_LCT_Developer`) is for quick iteration for developers, which could be done by using the Dev-Auth tool provided with the EOS SDK. Find [this](https://github.com/PlayEveryWare/eos_p
Instead of 'Find this for details' perhaps change it to 'Read this for more details.'.

2023-05-04 18:36 UTC, andrew-hirata-playeveryware commented on docs/readme_login.md
> +*They are omitted here to keep the file concise, more details could be found in plugin scripts*
I think we could add some references to the exact script that has the details to aid the user in finding it.

2023-05-04 22:58 UTC, Raxnam approved these changes

2023-05-04 22:58 UTC, Raxnam commented on docs/readme_login.md
> +More information about the distinction could be found [here](https://dev.epicgames.com/en-US/news/accessing-eos-game-services-with-the-connect-interface#a-brief-summary-of-auth-vs-connect-interfaces)
it may be good to link the `login_type_by_platform` for when to use each one

2023-05-15 18:17 UTC, andrew-hirata-playeveryware approved these changes

2023-05-16 18:08 UTC, merged