Feat(Transport Layer) Added functionality to Start Client
PlayEveryWare/eos_plugin_for_unity pull request #307
Opened 2023-06-07 22:37 UTC by Raxnam

added fields to copy and input PUID for hosting/joining servers via the network manager

2023-06-07 23:10 UTC, arthur740212 approved these changes

2023-06-08 18:11 UTC, andrew-hirata-playeveryware requested changes

2023-06-08 18:11 UTC, andrew-hirata-playeveryware commented on Assets/Scripts/Networking/EOSTransport.cs
> +        public String ServerUserIdToConnectToInput = null;
If this is editor only, shouldn't we wrap this in a UNITY_EDITOR conditional compile?

2023-06-09 17:35 UTC, andrew-hirata-playeveryware requested changes

2023-06-09 17:35 UTC, andrew-hirata-playeveryware commented on Assets/Scripts/Networking/EOSTransport.cs
> +        public String ServerUserIdToConnectToInput = null;
Oh my apologizes: I meant the fields and their uses should be wrapped, not just the usage.

2023-06-13 17:54 UTC, andrew-hirata-playeveryware approved these changes

2023-06-14 22:06 UTC, merged