Tidy
PlayEveryWare/eos_plugin_for_unity pull request #400
Opened 2023-09-15 23:29 UTC by paulhazen

# Cleaning up directory structure

This PR does not alter any functionality of the project, but changes where some things exist in the repository. There were a lot of items that we had in the root of the repository that more appropriately should have been placed somewhere else. 

> [!NOTE] 
> Code was only updated to reflect the new location of the moved files, and all docs were updated with new file locations.

These are the itemized changes that were made - each one happens in a single commit:

## Deleted files

- `Brewfile`
  _No need to install XCode on Mac, but not msbuild on windows or mono on linux, etc. While it's a helpful shortcut, it's not germaine to our project_

- DocFX
  _The content that the docfx tool can generate was checked in, it has been removed so that there is nolonger outdated documentation._

- `EOSZipInstallDescriptionConfigs`
  _Neither this directory, nor any of the files contained within are referenced anywhere in the project_

## Moved files

`bin`⟶ `tools/bin` 
`docfx_project` ⟶ `docs/docfx`
`accessible-urls.txt` ⟶ `config/accessible-urls.txt`
`EOSUnityPlugin_package_template` ⟶ `config/EOSUnityPlugin_package_template`
`PackageDescriptionConfigs` ⟶ `config/PackageDescriptions`
`UnityHelpers_Android` ⟶ `tools/src`

## New Directory Structure

### config
The `config` directory should contain any files related to the configuration of the project. These are typically JSON files or other small pieces of data that help define properties of the project and how it is to be built.

### tools
The `tools` directory contains utilities that are used outside of the plugin but are part of the plugin's development pipeline. Some of these tools exist in our repository as binary executable files, and some of these tools exist in the form of source code that is meant to be compiled. The former category lives in `tools/bin`, and the latter resides in `tools/src`.

## Result

<img width="412" alt="image" src="https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/1439891/7401168e-a08c-4d59-85ba-593bba2f5ca8">

> [!NOTE]
> Moving forward, for the sake of the long-term support of the project think carefully about where new files should live. It should be rare that a file needs to be added to the root of the repository.

2023-09-18 21:58 UTC, arthur740212 commented
Moving files look alright.
Some concerns about deleted file :
Brewfile : Definitely not good at the root folder, but for users, it probably could be in iOS/mac getting started docs.
Docfx : For updating the plugin website, not so sure if it will still work if removed
ZipInstall : I believe this is for updating the scripts when a new SDK drops. It a question for @pew-dahs if it is still usable given how the structure varies between each drop.

2023-09-19 00:42 UTC, paulhazen commented
> Moving files look alright. Some concerns about deleted file : Brewfile : Definitely not good at the root folder, but for users, it probably could be in iOS/mac getting started docs. Docfx : For updating the plugin website, not so sure if it will still work if removed ZipInstall : I believe this is for updating the scripts when a new SDK drops. It is a question for @pew-dahs if it is still usable given how the structure varies between each drop.

`Brewfile` - It could be there, but as I mentioned in the comment it's not something we similarly provide for other platforms, seems safe to assume if someone wants to use the plugin for iOS they would have as a pre-requisite knowledge of how to do unity development for it.

`Docfx` - Which website are you referring to? I can't seem to find anywhere it's being hosted. If you're just referring to generating a local copy of the static site, I made sure to update the [doc](https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/tidy/docs/generating_docfx_static_site.md) with the appropriate directories, and tested it as well to make sure it was working properly.

`ZipInstall` - Even if that is the case - such a file / directory could be placed in `tools/src` or `config`. But the files aren't referenced by anything else in the repo, so are kind of confusing to have in the root of the repository.

2023-09-19 17:35 UTC, arthur740212 commented
docfx is for the eos plugin unity page in PEWs website https://eospluginforunity.playeveryware.com/

2023-09-19 18:06 UTC, paulhazen commented
> docfx is for the eos plugin unity page in PEWs website https://eospluginforunity.playeveryware.com/

Nice, cool! With this context I think it makes even more sense to keep it in a sub-directory, since the website isn't actually a component of the open source project, but part of a separately hosted documentation.

2023-09-20 18:49 UTC, arthur740212 approved these changes

2023-09-22 22:41 UTC, andrew-hirata-playeveryware requested changes

2023-09-22 22:41 UTC, andrew-hirata-playeveryware commented on Brewfile
This was added specifically for people on our team to make it easier to install macOS utils. 
If possible, I'd actually like _more_ things that help automate what needs to be installed on a clean machine to help users get working on the project.

2023-09-22 22:41 UTC, andrew-hirata-playeveryware commented on tools/src/UnityHelpers_Android/UnityHelpers_Android/src/main/cpp/JNIHelpers.cpp
I believe this entire tool is deprecated, as I don't believe we need to invoke nor do anything with JNI directly anymore.

2023-09-22 22:41 UTC, andrew-hirata-playeveryware commented on Assets/Plugins/Source/Editor/Internal/BuildPackage.cs
I personally prefer `etc` to `config`, but I don't know other people on the team think or prefer.

2023-09-22 22:41 UTC, andrew-hirata-playeveryware commented on accessible-urls.txt
I believe this is (or was) needed for a restricted platform.

2023-09-22 22:41 UTC, andrew-hirata-playeveryware commented on docs/docfx/docfx.json
Were you able to confirm the tool still works with this?

2023-09-22 22:41 UTC, andrew-hirata-playeveryware commented on docfx_project/api/.manifest
All these files are some the commit files that were accidentally committed a few times.

2023-09-22 22:41 UTC, andrew-hirata-playeveryware commented on docs/docfx/docfx.json
Also, the docfx files are more configuration than documentation, aren't they?

2023-09-22 22:52 UTC, paulhazen commented on docs/docfx/docfx.json
> Also, the docfx files are more configuration than documentation, aren't they?

Yes - I agree. Good call.

2023-09-22 22:52 UTC, paulhazen commented on docfx_project/api/.manifest
It's not clear to me what you mean by this.

2023-09-22 22:53 UTC, paulhazen commented on docs/docfx/docfx.json
> Were you able to confirm the tool still works with this?

Yes I was.

2023-09-22 22:54 UTC, paulhazen commented on accessible-urls.txt
It is needed for the switch, and is referenced by `ProjectSettings.asset`, I moved the file and updated the reference in the `ProjectSettings.asset` file, so it's still there.

2023-09-22 22:54 UTC, paulhazen commented on Assets/Plugins/Source/Editor/Internal/BuildPackage.cs
I think I like that too - seems more canonical to me.

2023-09-22 22:55 UTC, paulhazen commented on tools/src/UnityHelpers_Android/UnityHelpers_Android/src/main/cpp/JNIHelpers.cpp
That was the impression I had from looking through everything, but because I could not be certain I left it in. I'll confirm this is the case and remove it once I do.

2023-09-22 22:57 UTC, paulhazen commented on Brewfile
That's a reasonable perspective. I have mixed feelings about it - but not strong ones. Could it be moved into a directory other than the root though? And to clarify - would it be good to add things like, a PowerShell script to setup the dev environment for windows, bash script for Linux, etc.? Would be pretty easy to do - and actually a similar script will need to be made anyways if we ever do automated testing on different platforms.

2023-09-23 02:24 UTC, paulhazen commented
Closing pull request as the description of the PR needs to be updated to match the changes made.

2023-09-28 23:14 UTC, paulhazen commented on Brewfile
Update: I actually moved this work into PR #417, since the task of writing setup scripts seemed like a distinct task from tidying up the directory structure. With that in mind, I'm going to mark this conversation as resolved for the time being. Feel free to re-open as you see fit.

2023-09-28 23:43 UTC, andrew-hirata-playeveryware requested changes

2023-09-28 23:43 UTC, andrew-hirata-playeveryware commented on Assets/Plugins/Source/Editor/Internal/BuildPackage.cs
> +                path = "config/PackageDescriptions/eos_dotunitypackage_package_desc.json";
Shouldn't this be `etc` if you changed everything to `etc`?

2023-09-28 23:43 UTC, andrew-hirata-playeveryware commented on Assets/Plugins/Source/Editor/Internal/UnityPackageCreationUtility.cs
> +            "config",
I think this should be etc now

2023-09-28 23:43 UTC, andrew-hirata-playeveryware commented on EOSZipInstallDescriptionConfigs/eos_public_platforms_description.json
Did you do this as a delete or as a `git mv`?

2023-09-28 23:43 UTC, andrew-hirata-playeveryware commented on NativeCode/DynamicLibraryLoaderHelper/DynamicLibraryLoaderHelper.sln
This file the same thing: if possible I'd prefer it to be a `git-mv` so that the git history is easily viewable

2023-09-28 23:43 UTC, andrew-hirata-playeveryware commented on ProjectSettings/ProjectSettings.asset
> +  switchAccessibleURLs: config/accessible-urls.txt
needs to be `etc`

2023-09-28 23:43 UTC, andrew-hirata-playeveryware commented on docs/creating_the_upm_package.md
> +This should by default be defined as `${WHATEVER_THE_GIT_REPO_IS_CALLED}/Assets/../config/PackageDescriptions/eos_package_description.json`.
should be `etc` not config now.

2023-09-28 23:43 UTC, andrew-hirata-playeveryware commented on docs/generating_docfx_static_site.md
> +2) Go to the `config/docfx/` dir in the repository.
should be `etc` now

2023-09-28 23:48 UTC, paulhazen commented
Closing PR for the following reasons:
1. Too many changes are introduced - they should be done more incrementally.
2. Too many *of those changes* do not make use of `git mv`, causing loss of easily followed history.

2023-09-28 23:48 UTC, closed without merging