Docs for using Steam SDK
PlayEveryWare/eos_plugin_for_unity pull request #433
Opened 2023-10-13 23:37 UTC by arthur740212

2023-10-16 19:50 UTC, Jason-PEW approved these changes
The EOS Dev portal changes frequently enough that we may not want to give instructions on how to set up the Identity Provider. And instead only link to their documentation on how to do it. Other than that, it looks good.

Note: I only read through the content, I don't know about the formatting.

2023-10-16 20:51 UTC, Raxnam approved these changes

2023-10-16 20:53 UTC, andrew-hirata-playeveryware requested changes

2023-10-16 20:53 UTC, andrew-hirata-playeveryware commented on docs/steam/readme_steam.md
> +There are several open source C# wrappers available.
We should mention which ones we have samples for.

2023-10-25 23:37 UTC, andrew-hirata-playeveryware approved these changes

2023-10-26 01:05 UTC, merged