Documentation Style Guide
PlayEveryWare/eos_plugin_for_unity pull request #434
Opened 2023-10-16 17:36 UTC by paulhazen

This PR introduces a new documentation style guide. The goal is to provide a set of standards for contributors to use when adding documentation to the repository. 

The document is an amalgam of how our documentation _currently_ is written, and how we _want_ our documentation to be written. Once this style guide is approved, I will begin the process of bringing our existing documentation into conformity with this guide.

_Only once all documentation has been made to conform_ will we make reference to this style guide in the README.md file. Currently it is an un-linked document that we will use internally to make documentation conform - then make the guide prominent to future contributors. This will avoid causing confusing discrepancies between the style guide and our existing documentation.

2023-10-17 02:09 UTC, andrew-hirata-playeveryware requested changes

2023-10-17 02:09 UTC, andrew-hirata-playeveryware commented on docs/docs_on_docs/doc_style_guide.md
> +Following the PlayEveryWare, Inc. logo should be the title of the document in pink text, followed immediately by a horizontal rule. To accomplish the pink text color, the typesetting system [LaTeX](h
Wasn't this something that broke recently? We still need to resolve this to get the pink text back.

2023-10-17 02:09 UTC, andrew-hirata-playeveryware commented on docs/docs_on_docs/doc_style_guide.md
> +Note that the `url` for an internal link is the value of the `name` attribute of the corresponding section link following a pound sign.
I would prefer we call this the `hash` or `number` sign instead of pound sign, to remove ambiguity for potential international readers of the text.

2023-10-17 02:09 UTC, andrew-hirata-playeveryware commented on docs/docs_on_docs/doc_style_guide.md
> +> If the list *can* be unordered, then it *should* be unordered.
I like this

2023-10-17 17:50 UTC, paulhazen commented on docs/docs_on_docs/doc_style_guide.md
> +Following the PlayEveryWare, Inc. logo should be the title of the document in pink text, followed immediately by a horizontal rule. To accomplish the pink text color, the typesetting system [LaTeX](h
Yes, good catch. I updated the example Markdown to reflect that, but I suppose I missed updating the description here.

2023-10-18 20:16 UTC, arthur740212 commented
The See Also Section looks unformatted, other than that the docs looks great

2023-10-18 20:17 UTC, arthur740212 approved these changes

2023-10-25 20:25 UTC, andrew-hirata-playeveryware approved these changes

2023-10-26 15:52 UTC, merged