fix: Rectified regression concerning the EOSBootstrapper and the EOS overlay.
PlayEveryWare/eos_plugin_for_unity pull request #564
Opened 2024-03-14 21:44 UTC by paulhazen

This PR fixes a regression that was introduced at some point during the recent changes to the build system.

Those changes errantly coupled the configuration and execution of Easy-Anti-Cheat and the Bootstrapper. 

The regression was such that if EAC was not configured, then the bootstrapper tool would not be utilized, which would prevent the friends overlay from displaying on Windows.

2024-03-14 21:53 UTC, arthur740212 approved these changes

2024-03-14 21:56 UTC, arthur740212 commented
Side question, was WAC implemented for mac or linux yet?

2024-03-14 22:39 UTC, andrew-hirata-playeveryware requested changes
Needs to be merged into the release branch instead of the development branch.

2024-03-14 23:55 UTC, paulhazen commented
> Side question, was WAC implemented for mac or linux yet?

EAC should be implemented for all three - but we don't have any automated tests around it so I can't be certain.

2024-03-15 20:05 UTC, andrew-hirata-playeveryware approved these changes

2024-03-15 22:01 UTC, merged