Unify implementation of ReadAllText
PlayEveryWare/eos_plugin_for_unity pull request #600
Opened 2024-04-12 15:06 UTC by paulhazen

This PR removes `AndroidFileIOHelper.cs` and the various places it is utilized, in favor of including the same logic conditionally compiled into the implementation of the `FileUtility.ReadAllText` method.

2024-04-12 18:26 UTC, andrew-hirata-playeveryware commented
This merge is being made into the wrong branch :/

2024-04-12 23:11 UTC, andrew-hirata-playeveryware commented
I like the idea of the FileUtility being the main point of entry for doing `ReadAllText`, but I think it's a better pattern for this project to keep the android code in it's own specific file, similar to how we segment other code by platform by putting it in it's own file, when it's possible.

2024-04-15 21:14 UTC, andrew-hirata-playeveryware requested changes
I like the idea of the FileUtility being the main point of entry for doing ReadAllText, but I think it's a better pattern for this project to keep the android code in it's own specific file, similar to how we segment other code by platform by putting it in it's own file, when it's possible. Besides that I'm fine with the change.

2024-04-16 18:11 UTC, andrew-hirata-playeveryware approved these changes

2024-04-16 18:21 UTC, arthur740212 approved these changes

2024-04-16 18:37 UTC, merged