chore(wsa, dynamic_loading): remove code associated with wsa dynamic
PlayEveryWare/eos_plugin_for_unity pull request #605
Opened 2024-04-15 23:54 UTC by andrew-hirata-playeveryware

# Intro 
Early in the project's history, there was some hopeful support for Windows Store App (WSA) added to the plugin. This was done to round out the number of platforms our plugin supported. Eventually, support for this platform fell by the wayside, and eventually was dropped. It actually might be more accurate to say that it wasn't ever really supported, and the code added to the plugin to support that platform doesn't _really_ work.

# Overview of changes
This particular PR removes the code that attempted to do 'clever' dynamic loading things so it could determine which version of Windows the plugin was running on, 32-bit or 64-bit. Given that it doesn't actually work, and makes the dynamic library loading code even more difficult to read, I believe it is time to get rid of the code

2024-04-15 23:59 UTC, paulhazen requested changes
Very minor change requested. Otherwise looks good.

2024-04-15 23:59 UTC, paulhazen commented on Assets/Plugins/Source/Core/EOSManager_DynamicLoading.cs
>  #if UNITY_64 || UNITY_WSA
If we are removing Windows Store Application support, we probably want to get rid of the second part of this conditional.

2024-04-15 23:59 UTC, paulhazen commented on Assets/Plugins/Source/Core/EOSManager_DynamicLoading.cs
> -            static extern void UnloadEOS();
Was this only ever used by WSA? The generic name is throwing me off I think.

2024-04-16 18:32 UTC, arthur740212 approved these changes
As long as these removed functions are actually WSA specific, should be good.

2024-04-16 19:05 UTC, paulhazen approved these changes

2024-04-16 19:06 UTC, merged