chore (Native Lib) : Restoring gitattributes with eol=lf instructions
PlayEveryWare/eos_plugin_for_unity pull request #734
Opened 2024-06-20 23:06 UTC by WispyMouse

Adds a .gitattributes file back to the NativeCode section. Only the file types that are actually in NativeCode are inside this. Added `eol=lf` to `*.cs`, which wasn't present before.

2024-06-20 23:07 UTC, arthur740212 approved these changes

2024-06-21 15:21 UTC, paulhazen approved these changes
One nit I have regarding the description for this PR: it doesn't explain the "why" behind this change. Does this resolve some problem? If so - explaining the problem and how this resolves it would be good.

Also - add yourself as the "Assignee" for this PR. Helps provide a record of who is responsible for the change - regardless of who ends up actually performing the merge. Also helps expand the visibility of your impact on the project.

2024-06-21 16:45 UTC, paulhazen requested changes
After some consideration - I think the comment I made on this PR probably merits a change - even though the changes I'm suggesting are not changes to the code changes, but changes I am requesting you make with respect to the format and administration of the PR as it exists within GitHub.

2024-06-21 18:18 UTC, paulhazen approved these changes

2024-06-21 18:24 UTC, merged