Log Filter
PlayEveryWare/eos_plugin_for_unity pull request #751
Opened 2024-06-26 22:19 UTC by paulhazen

This PR introduces a log filter, which can stop certain log messages from being logged, depending on a set of terms from which to exclude messages based off of.

This feature is disabled to "off", but for circumstances where the log window is overwhelmed with `<Redacted>` log messages from the EOS SDK, enabling this can help clarify what is going on.

2024-06-26 22:29 UTC, WispyMouse approved these changes

2024-06-26 22:50 UTC, arthur740212 approved these changes

2024-06-27 17:42 UTC, andrew-hirata-playeveryware requested changes
I believe this needs either a feature meeting or a task where we define what this is for.

2024-06-27 18:25 UTC, andrew-hirata-playeveryware approved these changes

2024-06-27 18:26 UTC, merged