refactor(docs): Move docs to new upm layout directory
PlayEveryWare/eos_plugin_for_unity pull request #780
Opened 2024-07-13 02:11 UTC by andrew-hirata-playeveryware

Move docs to a new UPM layout in an on going effort to deprecate the eos_plugin_for_unity_upm repo.

2024-07-15 07:41 UTC, paulhazen requested changes
This breaks most of the inter-documentation links contained within the markup. Reach out to me if you'd like assistance scripting a solution to this - it should be trivial, but in the current state we can't merge these changes in, as it will break the README.md document's functionality.

2024-07-15 17:41 UTC, andrew-hirata-playeveryware commented
@paulhazen I'd like to hear your suggestions!

2024-07-16 18:05 UTC, WispyMouse approved these changes

2024-07-16 19:04 UTC, paulhazen requested changes
I am still noticing changes. The way I checked things was by going to the README.md file from [your source branch](https://github.com/PlayEveryWare/eos_plugin_for_unity/tree/refactor/move_docs_to_upm_layout?tab=readme-ov-file), and clicking around on the links displayed there. I'm not certain what the correct way to rectify this is - just that the links still appear to not function properly.

2024-07-16 20:47 UTC, paulhazen approved these changes

2024-07-16 23:09 UTC, merged