fix: Consolidate test functionality of client sessions tests.
PlayEveryWare/eos_plugin_for_unity pull request #808
Opened 2024-07-27 20:13 UTC by paulhazen

2024-07-29 18:22 UTC, andrew-hirata-playeveryware approved these changes

2024-07-29 18:24 UTC, paulhazen commented on Assets/Tests/Common/EOSTestBase.cs
Please squash the two commits into one - for the sake of greater clarity.

2024-07-29 18:49 UTC, paulhazen commented on Assets/Tests/Common/EOSTestBase.cs
Done! Nice catch @paulhazen

2024-07-29 21:03 UTC, WispyMouse commented on Assets/Tests/PlayMode/ClientSessionTests.cs
>              yield return new WaitUntil(() => searchResult != null);
Not changed in scope; I wonder if WaitUntil should have a timeout here, so it doesn't roll infinitely.

2024-07-29 21:45 UTC, WispyMouse requested changes
Running the test twice currently always hangs Unity. I think the TearDown in EOSTestBase isn't implemented correctly. Either this needs to be determined as being out of the scope of this PR or needs to be fixed, since we can't really use the tests as is.

2024-07-29 23:47 UTC, paulhazen commented
> Running the test twice currently always hangs Unity. I think the TearDown in EOSTestBase isn't implemented correctly. Either this needs to be determined as being out of the scope of this PR or needs to be fixed, since we can't really use the tests as is.

Yeah, I noticed this as well. Out of scope as far as I can tell, as I experienced similar behavior with the tests in the first place.

2024-07-30 21:24 UTC, WispyMouse approved these changes
Changing to approve. A fix for the bug I identified is in this PR: https://github.com/PlayEveryWare/eos_plugin_for_unity/pull/811

2024-07-31 15:15 UTC, merged