Release-3.3.2 merge
PlayEveryWare/eos_plugin_for_unity pull request #868
Opened 2024-08-27 18:05 UTC by arthur740212

fix(log,config) : Using default log levels if config file doesn't exist
User were met with initialize errors when log level configs don't exist. It is caused by uncaught exceptions during file reading, leading to EOSManager.Init ceasing to complete. This fix catches those exceptions and continues the init using default log levels

2024-08-28 16:47 UTC, andrew-hirata-playeveryware requested changes

2024-08-28 16:47 UTC, andrew-hirata-playeveryware commented on com.playeveryware.eos/CHANGELOG.md
> +- Git Actions
This isn't following our change log format: we don't have subsections under each header.

2024-08-28 16:47 UTC, andrew-hirata-playeveryware commented on com.playeveryware.eos/CHANGELOG.md
> +  - chore: Update Unity version badge to 2021.3.16f1
These chores here don't need to be added.

2024-08-28 16:47 UTC, andrew-hirata-playeveryware commented on com.playeveryware.eos/CHANGELOG.md
> +  - chore: Update eos_package_description.json with new location of EOS SDK.
These chores about the package description file don't have to be added.

2024-08-28 16:47 UTC, andrew-hirata-playeveryware commented on com.playeveryware.eos/CHANGELOG.md
> +  - chore(eac,tool) : Allow anticheat integrity tool file path to recognize executables with no extension
This core about EAC sounds more like a feat or a fix

2024-08-28 16:47 UTC, andrew-hirata-playeveryware commented on com.playeveryware.eos/CHANGELOG.md
> +  - chore(sdk,source) : updated managed source for 1.16.3 hotfix
update source and update binaries for 1.16.3 can be collapsed into a single 'update eos sdk to 1.16.3' or similar phrasing.

2024-08-28 16:47 UTC, andrew-hirata-playeveryware commented on com.playeveryware.eos/CHANGELOG.md
> +  - feat: Create check-for-package-difference.yml
An argument could be made that this package difference feat doesn't need to be in here because it doesn't apply to the plugin itself.

2024-08-28 16:47 UTC, andrew-hirata-playeveryware commented on com.playeveryware.eos/CHANGELOG.md
> +  - feat: Add workflow to auto-update the unity version badge in README.md.
Same with this feat: it doesn't directly affect the plugin.

2024-08-28 16:47 UTC, andrew-hirata-playeveryware commented on com.playeveryware.eos/CHANGELOG.md
> +  - feature (Sessions): Code review feedback implemented
I don't think we need to include feedback commits like this.

2024-08-28 16:47 UTC, andrew-hirata-playeveryware commented on com.playeveryware.eos/CHANGELOG.md
> +  - rework(auth): Better variable names, namespace using moved, null propagation, 0-safe division
rework should probably changed either to feat or refactor.

2024-08-28 16:47 UTC, andrew-hirata-playeveryware commented on com.playeveryware.eos/CHANGELOG.md
> +  - docs (sessions): Responding to PR Feedback
don't need this 'responding to pr feedback' one

2024-08-28 16:47 UTC, andrew-hirata-playeveryware commented on com.playeveryware.eos/CHANGELOG.md
> +  - docs (Sessions): Continued effort in commenting everything
These lines about commenting could be condensed into 'add additional commenting'

2024-08-28 16:47 UTC, andrew-hirata-playeveryware commented on com.playeveryware.eos/CHANGELOG.md
> +  - refactor(sessions): Access level back!
This looks redundant with line 118

2024-08-28 16:47 UTC, andrew-hirata-playeveryware commented on com.playeveryware.eos/CHANGELOG.md
> +  - fix: Update the version of the checkout action to avoid warnings regarding running on a deprecated version of nodejs.
I don't think any of this git workflow/action things are needed for the plugin changelog.

2024-08-28 22:51 UTC, WispyMouse commented on com.playeveryware.eos/Runtime/Core/EOSManager.cs
> +
nit: remove line break, add break after if statement

2024-08-28 22:52 UTC, WispyMouse commented on com.playeveryware.eos/Runtime/Core/Utility/LogLevelUtility.cs
> +                    Debug.Log($"Exception when reading log level config, using default");
Consider Debug.LogException.

2024-08-28 22:56 UTC, WispyMouse approved these changes

2024-08-29 17:44 UTC, andrew-hirata-playeveryware approved these changes

2024-08-29 19:26 UTC, merged