Release 3.3.2
PlayEveryWare/eos_plugin_for_unity pull request #873
Opened 2024-08-29 19:28 UTC by arthur740212

2024-08-29 20:17 UTC, WispyMouse commented
The GitHub action is trying to look at `etc/PackageTemplate/package.json`. Looks like this got moved in this commit: https://github.com/PlayEveryWare/eos_plugin_for_unity/commit/371e0ead6d52ccbdc97f094178d93f0347ff7549

Because this set moves it from where it was in stable, I think we just ignore the failure on the action for now and go forward. I can tell that you've changed the package.json appropriately in this PR.

2024-08-29 20:25 UTC, WispyMouse approved these changes

2024-08-29 23:50 UTC, WispyMouse requested changes
#876 needs to be merged in to this after it is approved.

2024-08-30 00:03 UTC, WispyMouse approved these changes

2024-08-30 19:11 UTC, andrew-hirata-playeveryware approved these changes

2024-08-30 22:25 UTC, merged