(fix): Remove unreferenced files
PlayEveryWare/eos_plugin_for_unity pull request #885
Opened 2024-09-02 21:25 UTC by paulhazen

This PR removes two files and their corresponding `.meta` files that are not being used. `Assets/EOS/EOSManager.prefab` is removed because a practically identical version exists within `Assets/Plugins/`. The reason it exists at all is because we instruct users [here](https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/stable/com.playeveryware.eos/Documentation~/configure_plugin.md) to include `EOSManager.prefab` in their scenes from which they intend to use the EOS Plugin. 

> [!IMPORTANT]
> A _separate_ concern is that _neither_ `EOSManager.prefab` files existed where we instruct users to find it. Moving that to the correct location is outside the scope of this PR - which is limited to removing files that are not needed.

_This is another PR in the continuing effort to prepare to add more Unit Tests and is done preparatory to that so that when it is introduced that PR accomplishes the singular task of increasing code coverage._

#EOS-2060

2024-09-02 21:43 UTC, WispyMouse approved these changes
Approved.

`Assets/EOS/` gets put in `Runtime/EOS` in the built package. The location of the other prefab at `Assets/Plugins/EOSManager.prefab` will get put in `Runtime`. The users should be able to find both.

My main concern is that anyone who pulls the updated plugin, I *think* since this isn't sample code this could affect any number of users who are using the prefab. Upon updating the plugin, would the missing prefab cause their game to possibly break?

2024-09-03 17:45 UTC, andrew-hirata-playeveryware requested changes
This needs to update documentation to remove ref to the EOSManager, and the linked task needs to be updated with a new task that encapsulates the work.

2024-09-03 20:19 UTC, paulhazen commented
> This needs to update documentation to remove ref to the EOSManager, and the linked task needs to be updated with a new task that encapsulates the work.

I have narrowed the scope of the PR to only remove the file that was unreferenced by both code and documentation. The correct placement of the `EOSManager.prefab` file, and the removal of its duplicate can be relegated to another PR. 

I have also updated the linked task to reflect the work being done.

2024-09-03 23:34 UTC, andrew-hirata-playeveryware approved these changes

2024-09-03 23:47 UTC, merged