`FileSystemUtility.GetProjectPath()` to not use `Application.dataPath`
PlayEveryWare/eos_plugin_for_unity pull request #897
Opened 2024-09-05 20:15 UTC by paulhazen

This PR addresses an issue currently existing within the `development` branch that causes all the unit tests that derive from `EOSTestBase` to fail. The cause of this was access of the `Application.dataPath` property from within a thread other than the "main" Unity Thread.

This PR sidesteps that limitation by using a different means by which to infer the location of the project directory.

Thanks to @WispyMouse for documenting this issue and helping us find a solution.

 #EOS-2084

2024-09-09 17:44 UTC, WispyMouse commented on com.playeveryware.eos/Runtime/Core/Utility/FileSystemUtility.cs
> +            // Assuming the current directory is within the project (e.g., in the Editor or during Play mode)
This should have UNITY_EDITOR around it if it is only editor-time.

2024-09-09 17:45 UTC, WispyMouse commented on com.playeveryware.eos/Runtime/Core/Utility/FileSystemUtility.cs
> +            // Assuming the current directory is within the project (e.g., in the Editor or during Play mode)
Determine if a built UPM package will still resolve correctly here.

2024-09-09 19:04 UTC, WispyMouse requested changes
Request change in regards to UNITY_EDITOR and for validation that the built UPM package works.

2024-09-09 21:17 UTC, paulhazen commented on com.playeveryware.eos/Runtime/Core/Utility/FileSystemUtility.cs
> +            // Assuming the current directory is within the project (e.g., in the Editor or during Play mode)
I have moved the `UNITY_EDITOR` compile-time conditional and confirmed for certain that this functions properly when built as a UPM package.

2024-09-09 22:34 UTC, WispyMouse approved these changes

2024-09-10 17:43 UTC, andrew-hirata-playeveryware approved these changes

2024-09-10 17:43 UTC, merged