fix(config,IO) : Add missing if statement
PlayEveryWare/eos_plugin_for_unity pull request #898
Opened 2024-09-05 22:40 UTC by arthur740212

Without the if statement, it throws an exception always.
EOS-2087

2024-09-05 22:40 UTC, WispyMouse approved these changes

2024-09-06 20:35 UTC, paulhazen requested changes
I believe that a more correct implementation of this fix would be as follows. The following example maintains the singular conditional, but changes what happens if `!fileExists` evaluates to `false` based on the compile time conditional `UNITY_EDITOR` and provides a comment explaining the purpose of the compile time conditional.

This example would be to replace the contents of the file indicated from lines `293` to `307` as they currently exist in the `development` branch.
```c#
if (!fileExists)
{
    // This compile time conditional is here because if the file 
    // does not exist in the editor, then it should be written, 
    // whereas in a non-editor context the absence of a config file
    // warrants throwing an exception.
#if UNITY_EDITOR
    await WriteAsync();
#else
    // If the editor is not running, then the config file not
    // existing should throw an error.
    throw new FileNotFoundException(
        $"Config file \"{FilePath}\" does not exist.");
#endif
}
```

2024-09-09 17:59 UTC, arthur740212 commented
Updated

2024-09-09 21:13 UTC, paulhazen approved these changes

2024-09-09 21:30 UTC, andrew-hirata-playeveryware approved these changes

2024-09-10 17:44 UTC, merged