fix: Native Enum Parsing
PlayEveryWare/eos_plugin_for_unity pull request #953
Opened 2024-10-08 19:10 UTC by paulhazen

In a recent change to the native parsing, an error was made in the continue conditional. This PR resolves that issue and adds some comments to make it clearer what is happening.

2024-10-08 21:46 UTC, andrew-hirata-playeveryware approved these changes

2024-10-09 19:09 UTC, WispyMouse requested changes
Discussed offline, but essentially;

I believe strings_to_enum_values has c_strings. Map->find will compare the reference rather than the value. This results in failing to parse any strings, because it won't think anything is in the list.

This needs to use a strcmp or similar way of comparing c_strings. We could also change the key from a `const char*` to a `std::string` perhaps?

2024-10-10 18:38 UTC, paulhazen commented
> Discussed offline, but essentially;
> 
> I believe strings_to_enum_values has c_strings. Map->find will compare the reference rather than the value. This results in failing to parse any strings, because it won't think anything is in the list.
> 
> This needs to use a strcmp or similar way of comparing c_strings. We could also change the key from a `const char*` to a `std::string` perhaps?

This has been resolved now. Changing the key from `const char*` to `std::string` did the trick, good catch on that @WispyMouse!

2024-10-10 19:01 UTC, WispyMouse approved these changes

2024-10-10 20:20 UTC, merged