Fix/deployment override
PlayEveryWare/eos_plugin_for_unity pull request #965
Opened 2024-10-18 00:51 UTC by arthur740212

fix(init,config) : Remove false alarm when sandbox override is empty

EOS-2187

Should probably do EOS-2190 before the next release as they are highly related.

2024-10-24 17:31 UTC, paulhazen approved these changes

2024-10-25 18:43 UTC, WispyMouse approved these changes

2024-10-25 18:51 UTC, WispyMouse requested changes
As discussed in person: It appears as though our own EOS Project for this plugin uses an old deployment system. I suspect, based on the work that introduced the changes that this removes, that EOS may have a _different_ way of deploying for older projects. You'll require an Epic project with permission to see Epic Games Store's drop down and release management pipeline. Please test it in there, to validate that this code isn't necessary.

2024-10-25 18:52 UTC, WispyMouse commented
Or alternatively, remove the component of this PR that is related to the native code.

2024-10-28 19:33 UTC, WispyMouse approved these changes

2024-10-28 19:44 UTC, merged